# Generated by Django 2.2.3 on 2019-07-08 17:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='رویداد', max_length=250)),
                ('description', models.TextField(null=True)),
                ('img', models.ImageField(upload_to='images/')),
                ('capacity', models.IntegerField(default=10)),
                ('reserved_number', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('start_time', models.DateTimeField(default=datetime.datetime(2019, 7, 8, 17, 53, 54, 128102, tzinfo=utc), verbose_name='Start time')),
                ('finish_time', models.DateTimeField(default=datetime.datetime(2019, 7, 8, 17, 53, 54, 128102, tzinfo=utc), verbose_name='Finish time')),
                ('address', models.TextField(default='آدرس')),
                ('phone', models.CharField(max_length=12, null=True)),
                ('mail', models.EmailField(max_length=254, null=True)),
                ('instagram', models.CharField(max_length=30, null=True)),
                ('telegram', models.CharField(max_length=30, null=True)),
                ('creator', models.CharField(default='سازنده', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='JoinEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='status')),
                ('pending', models.BooleanField(default=True, verbose_name='pending')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
