# Generated by Django 2.2.3 on 2019-07-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='img',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='event',
            name='finish_time',
            field=models.DateTimeField(verbose_name='Finish time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(verbose_name='Start time'),
        ),
    ]
